### ISSUE TITLE
[Suggestion] Reload interval timer style

### ISSUE THREAD

**Issue by thomas-ashcraft** [blackwind/reload-plus#1]
As someone noticed at addon's page - its a little bit distracting.

Would be nice if that timer becomes half transparent when it have much time before triggering. I think 10-20 seconds can be a nice threshold.

And thus it is necessary to remove the transparency when you hover mouse over a tab. With mouse-hover functionality I even think that the timer can be half transparent all time. And lowering transparency before triggering becomes optionally.

Or maybe it would be nice to move timer into browser address bar.

**Comment by blackwind** [comment]
I prefer not to make styling changes like this for one or two users that will throw off the thousands of users who _don't_ want it. Instead, try the following style in [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) or [Stylish](https://addons.mozilla.org/firefox/addon/stylish/):

```
label[anonid="reloadplus-badge"] { opacity: 0.3 !important; }
label[anonid="reloadplus-badge"]:-moz-any([value="1"], [value="2"], [value="3"], [value="4"], [value="5"], [value="6"], [value="7"], [value="8"], [value="9"], [value="10"], [value="11"], [value="12"], [value="13"], [value="14"], [value="15"], [value="16"], [value="17"], [value="18"], [value="19"], [value="20"]) { opacity: 1 !important; }
```

**Comment by thomas-ashcraft** [comment]
But how about to move that timer into location bar, at least as option? Because auto reload option mostly needed at pinned tabs which contains only favicon without label, and timer stretches them.

**Comment by blackwind** [comment]
That's completely subjective. Personally, I never, ever use retry intervals on pinned tabs. Pinned tabs are typically for things like email and social media -- webapps that update automatically without reloading.

Another style to consider:

```
tab[pinned] label[anonid="reloadplus-badge"] { display: none !important; }
```

**Comment by blackwind** [comment]
Better still:

```
tab[pinned] label[anonid="reloadplus-badge"] { display: none !important; }
tab[pinned]:hover label[anonid="reloadplus-badge"] { display: inherit !important; }
```
