### ISSUE TITLE
5.0.3 Broken on Firefox 28

### ISSUE THREAD

**Issue by digideth** [blackwind/reload-plus#4]
The reload menu doesn't show up when clicking the reload button and you can't change any of the prefs in the add-on panel.

Not sure what version after 4.4.0.1 officially broke in FF28 but when I upgrade to 5.0.3 it is now broken.

If you don't want to fix it I would suggest updating the minimum browser to be above FF28.

If you need more info to fix this problem I am here to help!

Thanks!

**Comment by blackwind** [comment]
There's nothing I can think of that would've caused this, but I'll take your word. I've gone ahead and increased the minimum requirement for v5.0.0 and above to Firefox 29. Since v5.1.0 will require Firefox 38 anyway, there's no sense in doing a proper fix.
